version: "3.7"

services:
  all:
    image: alpine
    command: sh -C "echo start"
    depends_on:
      - frontend
      # - haproxy
      - server
      - ssa

  database:
    image: postgres:16.2-bullseye # higher than this?
    env_file: .env
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  frontend:
    env_file: .env
    environment:
      EXAMPLE: woof
    build:
      context: .
      dockerfile: app/Dockerfile
      target: frontend-dev
    ports:
      - 9229:9229
    volumes:
      - ./app:/opt/nlpssa-frontend
      - /opt/nlpssa-frontend/node_modules
      # - ~/.aws:/home/nlpstocksaapp/.aws:ro

  frontend-test:
    env_file: .env
    environment:
      ENV: test
    build:
      context: .
      dockerfile: app/Dockerfile
      target: frontend-dev

  # haproxy:
  #   build:
  #     context: docker/haproxy
  #     dockerfile: haproxy.dockerfile
  #   image: booboo/nlp-stock-sa-haproxy # this is probably incorrect :)
  #   depends_on:
  #     - client
  #     - server
  #   networks:
  #     default:
  #       aliases:
  #         - nlp-stock-sa.com
  #   ports:
  #     - 80:80
  #     - 443:443
  #   environment:
  #     EXAMPLE: woof

  server:
    depends_on:
      - database
    env_file: .env
    environment:
      EXAMPLE: woof
      WORKERS: 1
    build:
      context: .
      dockerfile: server/Dockerfile
      target: server-dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/opt/nlp-stock-sa
      # - ./server:/opt/nlp-stock-sa/server
      # - ~/.aws:/home/nlpstocksaapp/.aws:ro

  ssa:
    depends_on:
      - database
    env_file: .env
    environment:
      EXAMPLE: woof
      WORKERS: 1
    build:
      context: .
      dockerfile: server/Dockerfile
      target: ssa-dev
    ports:
      - "3001:3001"
    volumes:
      - ./ssa:/opt/nlp-stock-sa/ssa
      # - ~/.aws:/home/nlpstocksaapp/.aws:ro

volumes:
  db_volume:
